=== DimaXDD/Course2/4сем/ТПвИ/Lab3/files/validation.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" 
            elementFormDefault="qualified" 
            targetNamespace="http://msiter.ru" 
            xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="Container">
    <xs:complexType>
    <xs:sequence>
        <xs:element name="TaxiList">
        <xs:complexType>
        <xs:sequence>
            <xs:element name="Taxi" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                <xs:sequence>
                    <xs:element name="NameCar" type="xs:string" />
                    <xs:element name="Fuel" type="xs:double" />
                    <xs:element name="Speed" type="xs:positiveInteger" />
                    <xs:element name="Type">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="carType.economy"/>
                                <xs:enumeration value="carType.comfort"/>
                                <xs:enumeration value="carType.business"/>
                                <xs:enumeration value="carType.luxury"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        </xs:complexType>
    </xs:element>
    </xs:sequence>
</xs:complexType>
</xs:element>

</xs:schema>

=== DimaXDD/Course2/4сем/ТПвИ/Lab3/files/TaxiList.xml
<?xml version="1.0" encoding="utf-8"?>
<Container xmlns="http://msiter.ru" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://msiter.ru validation.xsd">
<TaxiList>
    <Taxi>
        <NameCar>Geely</NameCar>
        <Fuel>0.25</Fuel>
        <Speed>120</Speed>
        <Type>carType.economy</Type>
    </Taxi>
    <Taxi>
        <NameCar>BMW</NameCar>
        <Fuel>0.35</Fuel>
        <Speed>180</Speed>
        <Type>carType.comfort</Type>
    </Taxi>
    <Taxi>
        <NameCar>Mercedes</NameCar>
        <Fuel>0.40</Fuel>
        <Speed>200</Speed>
        <Type>carType.business</Type>
    </Taxi>
    <Taxi>
        <NameCar>Rolls-Royce</NameCar>
        <Fuel>0.5</Fuel>
        <Speed>220</Speed>
        <Type>carType.luxury</Type>
    </Taxi>
</TaxiList>
</Container>
